/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FinanceManagerRole;

import Business.Business;
import Business.Organization.AcademicAdminOrganization;
import Business.Organization.FinanceOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FinanceWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macmuffin
 */
public class HandleFinancesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HandleFinancesJPanel
     */
    JPanel workArea;
     UserAccount userAccount;
     FinanceOrganization financeOrganization;
      Business business;
     
    
   

    public HandleFinancesJPanel(JPanel mainWorkArea, UserAccount userAccount, FinanceOrganization financeOrganization, Business business) {
           initComponents();
        
        this.workArea=mainWorkArea;
            this.userAccount=userAccount;
            this.financeOrganization=financeOrganization;
            this.business=business;
            
            System.out.println("Inside HandleFinancesJPanel constructor");
            populateTable();
    }
    
    
      public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblFinancingRequests.getModel();

        model.setRowCount(0);
       
        
        for (WorkRequest request : financeOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getField1();
            row[2] = request.getField4();
//            row[3] = request;
//            row[3] = request.getStatus();

            model.addRow(row);
        }
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTotalBudget = new javax.swing.JLabel();
        txtTotalBudget = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFinancingRequests = new javax.swing.JTable();
        lblFinancingRequests = new javax.swing.JLabel();
        btnApproveBudget1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalBudget1 = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 0, 255));
        lblTitle.setText("Manage Finances");
        add(lblTitle);
        lblTitle.setBounds(330, 34, 159, 21);

        lblTotalBudget.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblTotalBudget.setForeground(new java.awt.Color(102, 51, 255));
        lblTotalBudget.setText("Total Budget:");
        add(lblTotalBudget);
        lblTotalBudget.setBounds(211, 117, 98, 17);

        txtTotalBudget.setEnabled(false);
        add(txtTotalBudget);
        txtTotalBudget.setBounds(340, 120, 200, 23);

        tblFinancingRequests.setBackground(new java.awt.Color(117, 205, 255));
        tblFinancingRequests.setForeground(new java.awt.Color(0, 102, 204));
        tblFinancingRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sender", "Teacher Name", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFinancingRequests);
        if (tblFinancingRequests.getColumnModel().getColumnCount() > 0) {
            tblFinancingRequests.getColumnModel().getColumn(0).setResizable(false);
            tblFinancingRequests.getColumnModel().getColumn(1).setResizable(false);
            tblFinancingRequests.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(107, 219, 597, 259);

        lblFinancingRequests.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblFinancingRequests.setForeground(new java.awt.Color(102, 51, 255));
        lblFinancingRequests.setText("Incoming Financing requests:");
        add(lblFinancingRequests);
        lblFinancingRequests.setBounds(107, 184, 215, 17);

        btnApproveBudget1.setBackground(new java.awt.Color(102, 51, 255));
        btnApproveBudget1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnApproveBudget1.setForeground(new java.awt.Color(255, 255, 255));
        btnApproveBudget1.setText("Approve Budget");
        btnApproveBudget1.setToolTipText("");
        btnApproveBudget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveBudget1ActionPerformed(evt);
            }
        });
        add(btnApproveBudget1);
        btnApproveBudget1.setBounds(570, 500, 146, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fin.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-390, 40, 1850, 580);

        txtTotalBudget1.setEnabled(false);
        add(txtTotalBudget1);
        txtTotalBudget1.setBounds(340, 120, 200, 23);
        add(txtSalary);
        txtSalary.setBounds(820, 510, 64, 23);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(840, 150, 78, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveBudget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveBudget1ActionPerformed
    int selectedRow = tblFinancingRequests.getSelectedRow();

    if (selectedRow >= 0) {
        // Assuming row[4] is the teacher's name
        String amount = txtSalary.getText(); 

        // Check if the salary has been added
        if ("-".equals(tblFinancingRequests.getValueAt(selectedRow, 2))) {
            FinanceWorkRequest request = (FinanceWorkRequest) tblFinancingRequests.getValueAt(selectedRow, 0);

            // Update the salary or perform necessary actions with the amount
            request.setField4(amount);
            
            // Set the result to "Approved" as per your logic
//            request.setResult("Approved");

            JOptionPane.showMessageDialog(null, "Salary added and request approved.", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Salary already added!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a request row!.");
        return;
    }

    populateTable();
    }//GEN-LAST:event_btnApproveBudget1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        populateTable();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveBudget1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFinancingRequests;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalBudget;
    private javax.swing.JTable tblFinancingRequests;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtTotalBudget;
    private javax.swing.JTextField txtTotalBudget1;
    // End of variables declaration//GEN-END:variables
}
