/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TeacherRole;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author macmuffin
 */
public class TeacherRequestSoftwareJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherRequestSoftwareJPanel
     */
    private JPanel workArea;
    
    public TeacherRequestSoftwareJPanel(JPanel workArea) {
        initComponents();
        this.workArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtQuantityNeeded = new javax.swing.JTextField();
        lblQuantityNeeded = new javax.swing.JLabel();
        btnSendSoftwareRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSoftwaresList = new javax.swing.JTable();
        lblSoftwaresList = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 102, 0));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 204, 0));
        lblTitle.setText("Request Software");

        btnBack.setBackground(new java.awt.Color(204, 255, 153));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblQuantityNeeded.setBackground(new java.awt.Color(0, 0, 0));
        lblQuantityNeeded.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblQuantityNeeded.setForeground(new java.awt.Color(204, 255, 153));
        lblQuantityNeeded.setText("Quantity:");

        btnSendSoftwareRequest.setBackground(new java.awt.Color(204, 255, 153));
        btnSendSoftwareRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSendSoftwareRequest.setText("Send Request");
        btnSendSoftwareRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSoftwareRequestActionPerformed(evt);
            }
        });

        tblSoftwaresList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Software Name", "Available Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSoftwaresList);
        if (tblSoftwaresList.getColumnModel().getColumnCount() > 0) {
            tblSoftwaresList.getColumnModel().getColumn(0).setResizable(false);
            tblSoftwaresList.getColumnModel().getColumn(1).setResizable(false);
            tblSoftwaresList.getColumnModel().getColumn(2).setResizable(false);
        }

        lblSoftwaresList.setBackground(new java.awt.Color(0, 0, 0));
        lblSoftwaresList.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblSoftwaresList.setForeground(new java.awt.Color(204, 255, 153));
        lblSoftwaresList.setText("Softwares list:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnBack)
                .addGap(238, 238, 238)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoftwaresList)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblQuantityNeeded)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantityNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnSendSoftwareRequest)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(29, 29, 29)
                .addComponent(lblSoftwaresList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendSoftwareRequest)
                    .addComponent(txtQuantityNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantityNeeded))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendSoftwareRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSoftwareRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendSoftwareRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendSoftwareRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuantityNeeded;
    private javax.swing.JLabel lblSoftwaresList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblSoftwaresList;
    private javax.swing.JTextField txtQuantityNeeded;
    // End of variables declaration//GEN-END:variables
}
