/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TeacherRole;

import Business.Business;
import Business.Organization.Organization;
import Business.Organization.StaffOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author macmuffin
 */
public class TeacherProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherProfileJPanel
     */
    private JPanel workArea;
    UserAccount userAccount;
    StaffOrganization staffOrganization;
    Business business;
    
    public TeacherProfileJPanel(JPanel workArea, UserAccount account, StaffOrganization staffOrganization, Business business) {
        initComponents();
 this.workArea = workArea;
    this.userAccount = account;
    this.staffOrganization = staffOrganization;
    this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewNotifications = new javax.swing.JButton();
        btnRequestLabEquipment = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 102, 0));
        setLayout(null);

        btnViewNotifications.setBackground(new java.awt.Color(204, 255, 153));
        btnViewNotifications.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnViewNotifications.setText("View Notifications from Management");
        btnViewNotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNotificationsActionPerformed(evt);
            }
        });
        add(btnViewNotifications);
        btnViewNotifications.setBounds(266, 195, 262, 40);

        btnRequestLabEquipment.setBackground(new java.awt.Color(204, 255, 153));
        btnRequestLabEquipment.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRequestLabEquipment.setText("Request Lab Equipment");
        btnRequestLabEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLabEquipmentActionPerformed(evt);
            }
        });
        add(btnRequestLabEquipment);
        btnRequestLabEquipment.setBounds(260, 250, 262, 40);

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 204, 0));
        lblTitle.setText("Teacher Profile");
        add(lblTitle);
        lblTitle.setBounds(20, 180, 171, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teacher.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-10, -10, 1390, 470);

        btnBack.setBackground(new java.awt.Color(204, 255, 153));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 50, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNotificationsActionPerformed
        // TODO add your handling code here:
        ViewNotifsFromMgmtJPanel viewNotifsJPanel = new ViewNotifsFromMgmtJPanel(workArea);
        workArea.add("ViewNotifsFromMgmtJPanel", viewNotifsJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewNotificationsActionPerformed

    private void btnRequestLabEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLabEquipmentActionPerformed
        // TODO add your handling code here:
        RequestLabEquipmentJPanel requestLabEquipJPanel = new RequestLabEquipmentJPanel(workArea,userAccount,staffOrganization,business);
        workArea.add("RequestLabEquipmentJPanel", requestLabEquipJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnRequestLabEquipmentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestLabEquipment;
    private javax.swing.JButton btnViewNotifications;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
