/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AcademicAdministration;

import Business.Business;
import Business.Organization.AcademicAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CurriculumWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anshikakhandelwal
 */
public class AcademicAdminmistratorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AcademicAdminmistratorJPanel
     */
   
    private JPanel userProcessContainer;
    private Business business;
    private UserAccount userAccount;
    //private Organization org;
    private AcademicAdminOrganization aaOrganization;

    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
   

    public AcademicAdminmistratorJPanel(JPanel userProcessContainer, UserAccount account, AcademicAdminOrganization academicAdminOrganization, Business business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
//        this.org = org;
        this.aaOrganization = academicAdminOrganization;

        populateTable();    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblWorkRequest.getModel();

        model.setRowCount(0);
        System.out.println(aaOrganization);
        
        for (WorkRequest request : aaOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getField1(); //.getSender().getEmployee().getName();
            row[2] = request.getField2();
            row[3] = request.getStatus();

            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnViewRecruitedTeachers = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Subject", "Description", "Approval status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequest);
        if (tblWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblWorkRequest.getColumnModel().getColumn(0).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(1).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(2).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(3).setResizable(false);
        }

        btnApprove.setBackground(new java.awt.Color(0, 102, 102));
        btnApprove.setForeground(new java.awt.Color(255, 153, 153));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnViewRecruitedTeachers.setBackground(new java.awt.Color(0, 102, 102));
        btnViewRecruitedTeachers.setForeground(new java.awt.Color(255, 153, 153));
        btnViewRecruitedTeachers.setText("View Recruited Teachers");
        btnViewRecruitedTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRecruitedTeachersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewRecruitedTeachers))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewRecruitedTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
         int selectedRow = tblWorkRequest.getSelectedRow();

        if (selectedRow >= 0) {
            CurriculumWorkRequest request = (CurriculumWorkRequest ) tblWorkRequest.getValueAt(selectedRow, 0);

            request.setStatus("Approved");

        } else {
            JOptionPane.showMessageDialog(null, "Please select a course to approve.");
            return;
        }
        populateTable();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnViewRecruitedTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRecruitedTeachersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewRecruitedTeachersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnViewRecruitedTeachers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWorkRequest;
    // End of variables declaration//GEN-END:variables
}
