/*
 * AdminWorkAreaJPanel.java
 *
 
 */
package ui.AdministrativeRole;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    JPanel workArea;
    Business business;
    private UserAccount userAccount;
    private Organization organization;
    Enterprise enterprise;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public AdminWorkAreaJPanel(JPanel workArea, UserAccount account, Organization organization, Business business) {
        initComponents();
        this.workArea = workArea;
        this.userAccount = account;
        this.business = business;
        this.organization = organization;
        this.enterprise = enterprise;
        if (business.getBudget() != null) {
            txtBudget.setText(String.valueOf(business.getBudget()));
            txtBudget.setEditable(false); // Make the text field non-editable
            btnBudget.setEnabled(false); // Make the button non-pressable
        }

    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        btnBudget = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));
        setLayout(null);

        userJButton.setForeground(new java.awt.Color(0, 153, 153));
        userJButton.setText("Manage Users");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton);
        userJButton.setBounds(290, 410, 290, 60);

        manageEmployeeJButton.setForeground(new java.awt.Color(0, 153, 153));
        manageEmployeeJButton.setText("Manage Employees");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton);
        manageEmployeeJButton.setBounds(290, 330, 290, 60);

        manageOrganizationJButton.setForeground(new java.awt.Color(0, 102, 102));
        manageOrganizationJButton.setText("Manage Organizations");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton);
        manageOrganizationJButton.setBounds(290, 260, 290, 50);

        lblTitle.setFont(new java.awt.Font("Devanagari Sangam MN", 2, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 204, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Administrative Work Area");
        add(lblTitle);
        lblTitle.setBounds(180, 120, 514, 53);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admins.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(780, -70, 270, 880);
        add(txtBudget);
        txtBudget.setBounds(290, 180, 220, 40);

        btnBudget.setText("btnBudget");
        btnBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBudgetActionPerformed(evt);
            }
        });
        add(btnBudget);
        btnBudget.setBounds(520, 190, 110, 23);

        jButton1.setText("View Analytics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(300, 500, 290, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(workArea, business);
        workArea.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(workArea, business.getOrganizationDirectory());
        workArea.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(workArea, business.getOrganizationDirectory());
        workArea.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void btnBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBudgetActionPerformed
        String budgetText = txtBudget.getText().trim();

    if (!budgetText.isEmpty()) {
        try {
            int newBudget = Integer.parseInt(budgetText);
            business.setBudget(newBudget);
            txtBudget.setEditable(false); // Make the text field non-editable
            btnBudget.setEnabled(false);

            // Display a message
            JOptionPane.showMessageDialog(null, "Budget set to the value: " + newBudget);

        } catch (NumberFormatException e) {
            // Handle the case where the entered text is not a valid integer
            JOptionPane.showMessageDialog(null, "Error: Please enter a valid integer for the budget.");
        }
    } else {
        // Display an error message if the text field is empty
        JOptionPane.showMessageDialog(null, "Error: Please enter a budget value.");
    }
    }//GEN-LAST:event_btnBudgetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         PlatformDataJPanel platformDataJPanel = new PlatformDataJPanel(workArea,business);
        workArea.add("PlatformDataJPanel", platformDataJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBudget;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables

}
