/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdministrativeRole;

import Business.Business;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author macmuffin
 */
public class PlatformDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlatformDataJPanel
     */
    private JPanel workArea;
    private Business business;
    
    public PlatformDataJPanel(JPanel workArea, Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        populateSystemData();
    }
    
    private void populateSystemData() {
        progressBar.setStringPainted(true);
        progressBar.setValue(8); // Set actual value of recruited teachers
        progressBar.setForeground(Color.BLUE);
        progressBar.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTotalStudents = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtTotalProfessors = new javax.swing.JLabel();
        lblFinancialMetrics = new javax.swing.JLabel();
        lblOverallFundsForResources = new javax.swing.JLabel();
        lblTeachersRecruited = new javax.swing.JLabel();
        txtOverallFundsForResources = new javax.swing.JTextField();
        lblBudgetTeachers = new javax.swing.JLabel();
        lblEnrollmentTargets = new javax.swing.JLabel();
        lblTotalEmployees = new javax.swing.JLabel();
        lblTarget = new javax.swing.JLabel();
        lblUserMetrics = new javax.swing.JLabel();
        txtTeachersRecruited = new javax.swing.JTextField();
        txtBudgetTeachers = new javax.swing.JTextField();
        lblTotalTeachers = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        txtTotalStudents.setFont(new java.awt.Font("Noteworthy", 1, 14)); // NOI18N
        txtTotalStudents.setForeground(new java.awt.Color(0, 204, 204));
        txtTotalStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnBack.setBackground(new java.awt.Color(255, 204, 255));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtTotalProfessors.setFont(new java.awt.Font("Noteworthy", 1, 14)); // NOI18N
        txtTotalProfessors.setForeground(new java.awt.Color(0, 204, 204));
        txtTotalProfessors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblFinancialMetrics.setFont(new java.awt.Font("Noteworthy", 3, 20)); // NOI18N
        lblFinancialMetrics.setForeground(new java.awt.Color(0, 102, 102));
        lblFinancialMetrics.setText("Financial Metrics");

        lblOverallFundsForResources.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblOverallFundsForResources.setForeground(new java.awt.Color(0, 204, 204));
        lblOverallFundsForResources.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOverallFundsForResources.setText("Overall funds granted for resources:");

        lblTeachersRecruited.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTeachersRecruited.setForeground(new java.awt.Color(0, 204, 204));
        lblTeachersRecruited.setText("Number of Teachers recruited:");

        txtOverallFundsForResources.setEnabled(false);

        lblBudgetTeachers.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBudgetTeachers.setForeground(new java.awt.Color(0, 204, 204));
        lblBudgetTeachers.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBudgetTeachers.setText("Overall budget spent on teacher salaries:");

        lblEnrollmentTargets.setFont(new java.awt.Font("Noteworthy", 3, 20)); // NOI18N
        lblEnrollmentTargets.setForeground(new java.awt.Color(0, 102, 102));
        lblEnrollmentTargets.setText("Yearly Teacher Enrollment Targets");

        lblTotalEmployees.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTotalEmployees.setForeground(new java.awt.Color(0, 204, 204));
        lblTotalEmployees.setText("Total Employess in the system:");

        lblTarget.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTarget.setForeground(new java.awt.Color(0, 204, 204));
        lblTarget.setText("Target: 100 teachers");

        lblUserMetrics.setFont(new java.awt.Font("Noteworthy", 3, 20)); // NOI18N
        lblUserMetrics.setForeground(new java.awt.Color(0, 102, 102));
        lblUserMetrics.setText("User Metrics");

        txtTeachersRecruited.setEnabled(false);

        txtBudgetTeachers.setEnabled(false);

        lblTotalTeachers.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTotalTeachers.setForeground(new java.awt.Color(0, 204, 204));
        lblTotalTeachers.setText("Total Teachers recruited for the enterprise:");

        progressBar.setBackground(new java.awt.Color(204, 204, 204));
        progressBar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        progressBar.setToolTipText("25%");

        lblTitle.setFont(new java.awt.Font("Noteworthy", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 102));
        lblTitle.setText("Platform Summarized Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserMetrics)
                                    .addComponent(lblTotalEmployees)
                                    .addComponent(btnBack)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFinancialMetrics)
                                .addComponent(txtTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalTeachers)
                                    .addComponent(txtTotalProfessors, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblTitle)))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblEnrollmentTargets)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTarget)
                            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lblTeachersRecruited))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOverallFundsForResources, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBudgetTeachers, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBudgetTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeachersRecruited, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOverallFundsForResources, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(26, 26, 26)
                .addComponent(lblUserMetrics)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalTeachers)
                            .addComponent(lblTotalEmployees))
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalProfessors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFinancialMetrics)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeachersRecruited)
                    .addComponent(txtTeachersRecruited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOverallFundsForResources)
                    .addComponent(txtOverallFundsForResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBudgetTeachers)
                    .addComponent(txtBudgetTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblEnrollmentTargets)
                .addGap(18, 18, 18)
                .addComponent(lblTarget)
                .addGap(29, 29, 29)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblBudgetTeachers;
    private javax.swing.JLabel lblEnrollmentTargets;
    private javax.swing.JLabel lblFinancialMetrics;
    private javax.swing.JLabel lblOverallFundsForResources;
    private javax.swing.JLabel lblTarget;
    private javax.swing.JLabel lblTeachersRecruited;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalEmployees;
    private javax.swing.JLabel lblTotalTeachers;
    private javax.swing.JLabel lblUserMetrics;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtBudgetTeachers;
    private javax.swing.JTextField txtOverallFundsForResources;
    private javax.swing.JTextField txtTeachersRecruited;
    private javax.swing.JLabel txtTotalProfessors;
    private javax.swing.JLabel txtTotalStudents;
    // End of variables declaration//GEN-END:variables
}
